backend:
name: github 
repo: florentk93/urban-jekyll-template

media_folder: "images"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Link"
            name: "links"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}