backend:
 name: github 
 repo: florentk93/urban-jekyll-template

media_folder: "images"
collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Link"
            name: "links"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
  - name: "clients"
    label: "Clients"
    identifier_field: name
    folder: "_clients"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "name"
        label: "Name"
        identifier_field: name
        widget: "string"
      - name: "subtitle"
        label: "Subtitle"
        widget: "string"
      - name: "external_url"
        label: "External URL"
        widget: "string"
      - name: "image_path"
        label: "Image Path"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: markdown